export const WORKLOAD_CATEGORIES = [
  {
    id: 1,
    slug: 'nlp',
    name: 'Natural Language Processing',
    icon: '🧠',
    color: 'from-violet-600 to-indigo-600',
    borderColor: 'border-violet-500',
    description: 'Process, understand, and generate human language with AI.',
    demos: [
      { slug: 'sentiment', name: 'Sentiment Analysis', active: true },
      { slug: 'sentence-similarity', name: 'Sentence Similarity', active: true },
      { slug: 'text-classification', name: 'Text Classification', active: false },
      { slug: 'ner', name: 'Named Entity Recognition', active: false },
      { slug: 'topic-modeling', name: 'Topic Modeling', active: false },
      { slug: 'language-detection', name: 'Language Detection', active: false },
      { slug: 'summarization', name: 'Summarization', active: false },
      { slug: 'paraphrasing', name: 'Paraphrasing', active: false },
      { slug: 'content-generation', name: 'Content Generation', active: false },
      { slug: 'code-generation', name: 'Code Generation', active: false },
      { slug: 'keyword-extraction', name: 'Keyword Extraction', active: false },
    ],
  },
  {
    id: 2,
    slug: 'vision',
    name: 'Computer Vision',
    icon: '👁️',
    color: 'from-cyan-600 to-blue-600',
    borderColor: 'border-cyan-500',
    description: 'Enable machines to interpret and understand visual information.',
    demos: [
      { slug: 'image-classification', name: 'Image Classification', active: false },
      { slug: 'object-detection', name: 'Object Detection (ResNet-50)', active: true },
      { slug: 'image-captioning', name: 'Image Captioning (BLIP)', active: true },
      { slug: 'face-detection', name: 'Face Detection', active: false },
      { slug: 'emotion-detection', name: 'Emotion Detection', active: false },
      { slug: 'image-generation', name: 'Image Generation', active: false },
      { slug: 'style-transfer', name: 'Style Transfer', active: false },
      { slug: 'super-resolution', name: 'Super Resolution', active: false },
    ],
  },
  {
    id: 3,
    slug: 'speech',
    name: 'Speech & Audio AI',
    icon: '🎙️',
    color: 'from-green-600 to-teal-600',
    borderColor: 'border-green-500',
    description: 'Convert, analyze, and generate speech and audio signals.',
    demos: [
      { slug: 'speech-to-text', name: 'Speech to Text', active: false },
      { slug: 'text-to-speech', name: 'Text to Speech', active: false },
      { slug: 'speaker-identification', name: 'Speaker Identification', active: false },
      { slug: 'voice-cloning', name: 'Voice Cloning', active: false },
      { slug: 'sound-classification', name: 'Sound Classification', active: false },
    ],
  },
  {
    id: 4,
    slug: 'document',
    name: 'Document Intelligence',
    icon: '📄',
    color: 'from-orange-600 to-amber-600',
    borderColor: 'border-orange-500',
    description: 'Extract, understand, and search content from documents.',
    demos: [
      { slug: 'ocr', name: 'OCR (Azure AI Vision)', active: true },
      { slug: 'table-extraction', name: 'Table Extraction', active: false },
      { slug: 'invoice-processing', name: 'Invoice Processing', active: false },
      { slug: 'document-summarization', name: 'Document Summarization', active: false },
      { slug: 'document-search', name: 'Document Search', active: false },
    ],
  },
  {
    id: 5,
    slug: 'ml',
    name: 'Machine Learning',
    icon: '📊',
    color: 'from-pink-600 to-rose-600',
    borderColor: 'border-pink-500',
    description: 'Classical ML algorithms for prediction, classification, and discovery.',
    demos: [
      { slug: 'regression', name: 'Regression', active: false },
      { slug: 'classification', name: 'Classification', active: false },
      { slug: 'clustering', name: 'Clustering', active: false },
      { slug: 'anomaly-detection', name: 'Anomaly Detection', active: false },
      { slug: 'time-series', name: 'Time Series Forecasting', active: false },
    ],
  },
  {
    id: 6,
    slug: 'deep-learning',
    name: 'Deep Learning',
    icon: '🔬',
    color: 'from-yellow-600 to-orange-600',
    borderColor: 'border-yellow-500',
    description: 'Neural networks from CNNs to Transformers and GANs.',
    demos: [
      { slug: 'cnn', name: 'Convolutional Neural Networks', active: false },
      { slug: 'rnn-lstm', name: 'RNN / LSTM Networks', active: false },
      { slug: 'transformer', name: 'Transformer Models', active: false },
      { slug: 'bert', name: 'BERT-based Models', active: false },
      { slug: 'gpt', name: 'GPT-based Models', active: false },
      { slug: 'gans', name: 'Generative Adversarial Networks', active: false },
    ],
  },
  {
    id: 7,
    slug: 'agentic',
    name: 'Agentic AI & Automation',
    icon: '🤖',
    color: 'from-red-600 to-pink-600',
    borderColor: 'border-red-500',
    description: 'Autonomous agents that plan, reason, and take actions.',
    demos: [
      { slug: 'task-agents', name: 'Task Agents', active: false },
      { slug: 'autonomous-agents', name: 'Autonomous Agents', active: false },
      { slug: 'multi-agent', name: 'Multi-Agent Systems', active: false },
      { slug: 'code-agents', name: 'Code Agents', active: false },
    ],
  },
  {
    id: 9,
    slug: 'search',
    name: 'Search Algorithms',
    icon: '🔍',
    color: 'from-emerald-600 to-teal-600',
    borderColor: 'border-emerald-500',
    description: 'Explore classical and AI-powered search techniques interactively.',
    demos: [
      { slug: 'semantic-search', name: 'Semantic Search', active: true },
      { slug: 'keyword-search', name: 'Keyword Search', active: true },
      { slug: 'linear-search', name: 'Linear Search', active: true },
      { slug: 'binary-search', name: 'Binary Search', active: true },
      { slug: 'heuristic-search', name: 'Heuristic Search (A*)', active: true },
      { slug: 'fuzzy-search', name: 'Fuzzy Search', active: true },
      { slug: 'full-text-search', name: 'Full-Text Search', active: true },
      { slug: 'faceted-search', name: 'Faceted Search', active: true },
    ],
  },
  {
    id: 10,
    slug: 'python',
    name: 'Python Learning',
    icon: '🐍',
    color: 'from-green-600 to-teal-600',
    borderColor: 'border-green-500',
    description: 'Learn Python interactively — from basics to data science and automation.',
    demos: [
      { slug: 'variables-types', name: 'Variables & Data Types', active: false },
      { slug: 'control-flow', name: 'Control Flow', active: false },
      { slug: 'functions', name: 'Functions & Scope', active: false },
      { slug: 'lists-dicts', name: 'Lists & Dictionaries', active: false },
      { slug: 'oop', name: 'Object-Oriented Programming', active: false },
      { slug: 'file-io', name: 'File I/O', active: false },
      { slug: 'comprehensions', name: 'List Comprehensions', active: false },
      { slug: 'error-handling', name: 'Error Handling', active: false },
      { slug: 'numpy-basics', name: 'NumPy Basics', active: false },
      { slug: 'pandas-basics', name: 'Pandas Basics', active: false },
      { slug: 'matplotlib', name: 'Data Visualization', active: false },
      { slug: 'regex', name: 'Regular Expressions', active: false },
    ],
  },
  {
    id: 8,
    slug: 'analytics',
    name: 'Data & Analytics AI',
    icon: '📈',
    color: 'from-teal-600 to-cyan-600',
    borderColor: 'border-teal-500',
    description: 'AI-powered data exploration, visualization, and AutoML.',
    demos: [
      { slug: 'data-visualization', name: 'Data Visualization', active: false },
      { slug: 'eda', name: 'Exploratory Data Analysis', active: false },
      { slug: 'automl', name: 'AutoML', active: false },
    ],
  },
]
